DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS employee;


CREATE TABLE `department` (`id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT, `name` VARCHAR(30));

CREATE TABLE `roles` (`id` INTEGER PRIMARY KEY AUTO_INCREMENT, `title` VARCHAR(30), `salary` DECIMAL, `department_id` INTEGER);

CREATE TABLE `employee` (`id` INTEGER PRIMARY KEY AUTO_INCREMENT, `first_name` VARCHAR(30), `last_name` VARCHAR(30), `role_id` INTEGER, `manager_id` INTEGER NULL);